<?php
/**
 * Copyright © 2016 Epay Design. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
/**
 * @var $block \Epaytech\Epay\Block\Info
 */
?>
<dl class="payment-method epay">
    <dt class="title"><?php echo $block->escapeHtml($block->getMethod()->getTitle()) ?></dt>
    <dd class="content">
        <?php if ($block->getInfo()->getLastTransId() == ''): ?>
            <?php echo __('No transaction ID recorded.') ?>
        <?php else: ?><?php echo __('Epay Transaction ID: %1', $this->escapeHtml($block->getInfo()->getLastTransId())) ?>
        <?php endif; ?>    </dd>
</dl>
