<?php
/**
 * Copyright © 2016 Epay Design. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
/**
 * @var $block \Epaytech\Epay\Block\Info
 */
?>

<?php echo $block->escapeHtml($block->getMethod()->getTitle()) ?>
<?php if ($block->getInfo()->getLastTransId() == ''): ?>
    <br /><?php echo __('No transaction ID recorded.') ?>
<?php else: ?>
    <br /><?php echo __('Epay Transaction ID: %1', $this->escapeHtml($block->getInfo()->getLastTransId())) ?>
<?php endif; ?>
